version: '3.7'
services:
  mysql:
    image: mysql:8.0.18
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=qwerty
      - POSTGRES_PASSWORD=ytrewq

  nodejs:
    build: ./gate-simulator
    ports:
      - '9999:9999'